- hosts: localhost
  connection: local
  tasks:
    - debug: var=groups
    - debug: var=hostvars

- hosts: all
  gather_facts: false
  tasks:
    - name: wait for host to come up
      wait_for_connection:

- import_playbook: '{{ openshift_ansible_dir }}/playbooks/prerequisites.yml'
- import_playbook: '{{ openshift_ansible_dir }}/playbooks/deploy_cluster.yml'
